livret_generer:
    path:   /generer
    defaults: { _controller: LivretBundle:Default:generer }

livret_homepage:
    path:     /
    defaults: { _controller: LivretBundle:Default:index }

livret_remplir:
    path:   /remplir
    defaults: { _controller: LivretBundle:Default:remplir }

livret_consulter:
    path:   /consulter
    defaults: { _controller: LivretBundle:Default:consulter }

livret_remplir_quinzaine:
    path:   /remplir-quinzaine
    defaults: { _controller: LivretBundle:Default:remplirQuinzaine }