livret_generer:
    path:   /generer
    defaults: { _controller: LivretBundle:Default:generer }

livret_export:
    path:   /export
    defaults: { _controller: LivretBundle:Default:export }

livret_homepage:
    path:     /
    defaults: { _controller: LivretBundle:Default:index }

livret_remplir:
    path:   /remplir
    defaults: { _controller: LivretBundle:Default:remplir }

livret_consulter:
    path:   /consulter
    defaults: { _controller: LivretBundle:Default:consulter }

livret_quinzaine:
    path:   /quinzaine
    defaults: { _controller: LivretBundle:Default:quinzaine }

livret_quinzaine_ajouter:
    path:   /quinzaine/ajouter
    defaults: { _controller: LivretBundle:Default:quinzaineAjouter }
    
livret_mentions:
    path:   /mentions
    defaults: { _controller: LivretBundle:Default:mentions }

livret_aide:
    path:   /aide
    defaults: { _controller: LivretBundle:Default:aide }

livret_aideConsult:
    path:   /aideConsult
    defaults: { _controller: LivretBundle:Default:aide_consultation }
    
livret_choix_apprenti:
    path:   /consulter/apprenti
    defaults: { _controller: LivretBundle:Default:choisirApprenti }

livret_save_bdd:
    path:    /consulter/saveLivret
    defaults: { _controller: LivretBundle:Default:saveLivret }

livret_signer:
    path:    /consulter/signer
    defaults: { _controller: LivretBundle:Default:signer }

livret_ajouter_fichier:
    path:   /consulter/fichier
    defaults: { _controller: LivretBundle:Default:ajouterFichier }

livret_quinzaine_formation_ajouter:
    path:   /quinzaine/formation/ajouter
    defaults: { _controller: LivretBundle:Default:addItemFormation }

livret_quinzaine_entreprise_ajouter:
    path:   /quinzaine/entreprise/ajouter
    defaults: { _controller: LivretBundle:Default:addItemEntreprise }

livret_quinzaine_formation_item_delete:
    path:   /quinzaine/formation/supprimer
    defaults: { _controller: LivretBundle:Default:removeItemFormation }

livret_quinzaine_entreprise_item_delete:
    path:   /quinzaine/entreprise/supprimer
    defaults: { _controller: LivretBundle:Default:removeItemEntreprise }

livret_quinzaine_tuteur_item_ajouter:
    path:   /quinzaine/tuteur/ajouter
    defaults: { _controller: LivretBundle:Default:addItemTuteur }

livret_quinzaine_tuteur_maitrise:
    path:   /quinzaine/tuteur/maitrise
    defaults: { _controller: LivretBundle:Default:addMaitriseComp }

livret_quinzaine_tuteur_description:
    path:   /quinzaine/tuteur/description
    defaults: { _controller: LivretBundle:Default:addDescriptionComp }