livret_generer:
    path:   /generer
    defaults: { _controller: LivretBundle:Default:generer }

livret_export:
    path:   /export
    defaults: { _controller: LivretBundle:Default:export }

livret_homepage:
    path:     /
    defaults: { _controller: LivretBundle:Default:index }

livret_remplir:
    path:   /remplir
    defaults: { _controller: LivretBundle:Default:remplir }

livret_consulter:
    path:   /consulter
    defaults: { _controller: LivretBundle:Default:consulter }

livret_quinzaine:
    path:   /quinzaine
    defaults: { _controller: LivretBundle:Default:quinzaine }

livret_quinzaine_ajouter:
    path:   /quinzaine/ajouter
    defaults: { _controller: LivretBundle:Default:quinzaineAjouter }

livret_aide:
    path:   /aide
    defaults: { _controller: LivretBundle:Default:aide }

livret_choix_apprenti:
    path:   /consulter/apprenti
    defaults: { _controller: LivretBundle:Default:choisirApprenti }

livret_save_bdd:
    path:    /consulter/saveLivret
    defaults: { _controller: LivretBundle:Default:saveLivret }